[build]
  command = "npm run build & npm install"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "10"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
