backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "/images"
collections:
- name: "blog"
  label: "Blog"
  folder: "pages"
  create: true
  fields:
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Body", name: "body", widget: "markdown" }
